# Generated by Django 3.0.5 on 2020-05-03 14:52

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('candidate_name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('vote_count', encrypted_fields.fields.EncryptedBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('election_name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.CharField(max_length=300, primary_key=True, serialize=False, unique=True)),
                ('voter_name', encrypted_fields.fields.EncryptedCharField(max_length=100)),
                ('has_voted', models.BooleanField(default=False)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('voted_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.Candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election'),
        ),
    ]
